<a href="https://colab.research.google.com/github/jaewonleehyeyum/orm/blob/main/0104_%EC%8B%9C%ED%80%80%EC%8A%A4%EC%9E%90%EB%A3%8C%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 시퀀스 자료형

In [1]:
# 1.1 인덱싱
        #(-) 54321
            #01234
example = 'abcde'
print(example[0]) # 출력 : a
print(example[2]) # 출력 : c
print(example[-1]) # 출력 : e

a
c
e


In [2]:
# 1.2 슬라이싱
            #54321
            #01234
example = 'abcde'
print(example[-4:-1]) # 출력 : bcd

bcd


In [5]:
range(10)[3] # 출력: 3
range(100)[::5] # 출력: range(0, 100, 5)

range(0, 100, 5)

In [6]:
# 1.3 특정항목 포함 여부
example = 'abcde'
print('a' in example)

True


In [7]:
print('z' not in example)

True


In [8]:
# 1.4 연결 & 반복
example1 = 'abcde'
example2 = 'f'
print(example1 + example2) # 출력: abcdef
print(example2 * 3)        # 출력 : fff

abcdef
fff


In [9]:
# 내장함수를 사용!
example = 'abcde'
print(len(example)) # 출력: 5
print(min(example)) # 출력: a
print(max(example)) # 출력: e

5
a
e


# 2. 시퀀스 자료형의 패킹과 언패킹

In [10]:
# 2.1 튜플 패킹
# 튜플 패킹

packed_tuple = 1, 2, 3, 4
print(packed_tuple) # 출력 : (1, 2, 3, 4)
type(packed_tuple)

(1, 2, 3, 4)


tuple

In [11]:
tuple_example = 1
print(tuple_example)
type(tuple_example)

1


int

In [12]:
# 2.2 언패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4
print(packed_tuple)

(1, 2, 3, 4)


In [13]:
# 튜플 언패킹
a, b, c, d = packed_tuple
print(a)
print(b)
print(c)
print(d)

1
2
3
4


In [14]:
# 다양한 패킹/언패킹
# range는 0부터 n-1까지 숫자를 생성하는 함수
a, b, c = range(3) #0,1,2
print(range(3))
print(a, b, c)

range(0, 3)
0 1 2


In [17]:
a, b, c, d, e = 'hello'
print(a)
print(b)
print(c)
print(d)
print(e)

h
e
l
l
o


In [18]:
a, b = [10, 20]
print(a)
print(b)

10
20


In [22]:
total_sum = 0

for i in range(5): #0,1,2,3,4
    total_sum += 1
    print(total_sum)
print(total_sum)

1
2
3
4
5
5


In [23]:
# 별표를 이용한 언패킹
first, *middle, last = [1, 2, 3, 4, 5]
print(first)
print(middle)
print(last)

1
[2, 3, 4]
5


# 2. 리스트

In [24]:
# 리스트의 필요성

x1 = 100
x2 = 200
x3 = 300

x = [100, 200, 300]

In [26]:
# 리스트의 장점 : 여러가지 자료형을 넣을 수 있다.
z = [1, 'apple', 2.5, ['a', 'b'], (1, 2), True]
print(z[0])
print(z[1])
print(z[2])
print(z[3])
print(z[4])
print(z[5])

1
apple
2.5
['a', 'b']
(1, 2)
True


In [28]:
z = [
              1,
              'apple',
              2.5,
              ['a', 'b'],
              (1, 2)
]
print(z[0])
print(z[1])
print(z[2])
print(z[3])
print(z[4])

1
apple
2.5
['a', 'b']
(1, 2)


In [29]:
# 2.2 리스트 값 수정

a = [1, 2, 3, 4, 5]
a[0] = 10000
print(a)

[10000, 2, 3, 4, 5]


In [30]:
# 문자열은 변경할 수 없다
s = 'licat'
print(s[0])
s[0] = 'k'

l


TypeError: ignored

In [31]:
# 3. 리스트 안에 리스트

b = [[10, 20, 30], [1, 2, 3]]
print(b[1][2]) #출력: 3

'''
이 코드는 중첩된 리스트(리스트 안에 리스트)를 다루고 있습니다. 코드를 단계별로 설명하겠습니다:

1. `b = [[10, 20, 30], [1, 2, 3]]`: 여기서 `b`는 두 개의 리스트를 원소로 갖는 리스트입니다. 첫 번째 내부 리스트는 `[10, 20, 30]`이고, 두 번째 내부 리스트는 `[1, 2, 3]`입니다.

2. `print(b[1][2])`: 이 부분은 `b` 리스트의 원소에 접근하는 방식입니다.
   - `b[1]`: 여기서 `b[1]`은 `b`의 두 번째 원소를 의미합니다. 파이썬에서 리스트의 인덱스는 0부터 시작하므로, `b[1]`은 `[1, 2, 3]`입니다.
   - `b[1][2]`: 이제 `b[1]`이 `[1, 2, 3]`이므로, 여기서 `[2]`는 이 리스트의 세 번째 원소를 가리킵니다. 이 역시 인덱스가 0부터 시작하므로, `[1, 2, 3]`의 세 번째 원소는 `3`입니다.

따라서 `print(b[1][2])`는 `3`을 출력합니다. 이는 `b`의 두 번째 리스트 `[1, 2, 3]`의 세 번째 원소에 해당합니다.
'''

3


In [32]:
print(b)
print(b[0])
print(b[1])
print(b[0][2])

[[10, 20, 30], [1, 2, 3]]
[10, 20, 30]
[1, 2, 3]
30


In [ ]:
나이 직업구분
10    1
20    2
30    3

In [34]:
# 리스트의 덧셈
a = [1, 2, 3, 4, 5] # +[6,7,8]
b = [6, 7, 8]

print(a + b) #출력: [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


In [35]:
I = [1, 2, 3]
print(type(I))
print(I)
print(I * 3)
print(I + I)

<class 'list'>
[1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [36]:
from re import L
import numpy as np

I = [1, 2, 3]
I = np.array(I)
print(I)
print(type(I))
print(I * 3)
print(I + I)
# 너무 당연하게 요소를 붙이는 것이다라고 생각하지 않아야함

[1 2 3]
<class 'numpy.ndarray'>
[3 6 9]
[2 4 6]


In [38]:
# 슬라이싱 실습

I = [1, 2, 3, 4, 5]

print(I[:])     # 출력 : [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


In [39]:
print(I[::-1]) # 출력 : [1, 3, 5]

[5, 4, 3, 2, 1]


In [40]:
print(I[0:4][::-1]) # 출력 : [4, 3, 2, 1]

[4, 3, 2, 1]


In [ ]:
# 데이터가 크다. 내가 원하는 대로 데이터를 추출하고 싶다.
# 1. 샘플링 -> 1억개 데이터 -> 천개! -> 리스트 슬라이싱! 메서드! -> 1억개 데이터!

In [41]:
I = [1, 2, 3, 4, 5]
print(I[10:20]) # 출력: []

'''
이 Python 코드의 특정 부분은 리스트 `I`에서 슬라이싱을 사용하여 요소들을 추출하고 있습니다. 리스트 `I`는 `[1, 2, 3, 4, 5]`로 정의되어 있습니다.

`print(I[10:20])` 부분을 살펴보겠습니다:
- `I[10:20]`는 리스트 `I`에서 인덱스 10부터 인덱스 19까지의 요소들을 추출하라는 의미입니다.
- 하지만, 리스트 `I`의 길이는 5이므로, 인덱스 10부터 19까지의 요소는 존재하지 않습니다.
- 파이썬에서 리스트 슬라이싱은 범위를 벗어난 인덱스에 대해 오류를 발생시키지 않고, 대신 빈 리스트 `[]`를 반환합니다.
- 따라서, `print(I[10:20])`는 빈 리스트 `[]`를 출력합니다.

이 코드는 파이썬의 리스트 슬라이싱 기능이 범위를 벗어난 인덱스에 유연하게 대응하는 방식을 보여주는 좋은 예입니다.
'''

[]
